# More config options at https://rust-lang.github.io/rustfmt
edition                     = "2021"

# Available in nightly builds/channels!
# blank_lines_upper_bound     = 3 # Max number of consecutive empty lines
# wrap_comments               = true
# condense_wildcard_suffixes  = true
# control_brace_style         = "ClosingNextLine"
# struct_lit_single_line      = false
